name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [linux, windows, macos]
        include:
          - name: linux
            os: ubuntu-latest
            artifact_path: target/release/gunfollower
            asset_name: gunfollower
          - name: windows
            os: windows-latest
            artifact_path: target/release/gunfollower.exe
            asset_name: gunfollower-windows.exe
          - name: macos
            os: macos-latest
            artifact_path: target/release/gunfollower
            asset_name: gunfollower

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release --locked

      - name: Rename binary
        run: mv ${{ matrix.artifact_path }} ${{ matrix.asset_name }}

      - name: Create NPM Release
        run: mkdir -p builds/gunfollower-${{ matrix.name }} && cp ${{ matrix.asset_name }} builds/gunfollower-${{ matrix.name }} && tar -C builds -czvf gunfollower-${{ matrix.name }}.tar.gz gunfollower-${{ matrix.name }}

      - name: Release binary
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            gunfollower-${{ matrix.name }}.tar.gz
            ${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  changelog:
    name: Update Changelog
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Release Changelog
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  homebrew:
    needs: changelog
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"
      - uses: mislav/bump-homebrew-formula-action@v1
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: gunfollower
          homebrew-tap: DarthBenro008/homebrew-gunfollower
          base-branch: master
          download-url: https://github.com/DarthBenro008/gunfollower/releases/latest/download/gunfollower-macos.tar.gz
          commit-message: |
            {{formulaName}} {{version}}

            bump: Update gunfollower version
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}